#!/bin/zsh

# Install all (most) dependencies
# This also serves as a list of dependencies

yay -S --needed \
\
`# Standard`\
awesome \
kitty \
neovim \
firefox-developer-edition \
python-pywal \
playerctl \
pamixer \
rsync \
byobu \
zsh \
xorg-xmodmap \
picom \
unclutter \
redshift \
xclip \
polkit-gnome \
arc-icon-theme \
acpi \
\
`# Aur`\
python-pywalfox \
pywal-discord-git \
wal-telegram-git \
lf-git \
ctpv-git \
nvim-packer-git \
